package com.bbn.akbc.neolearnit.labelers;

import com.bbn.akbc.neolearnit.common.Annotation;
import com.bbn.akbc.neolearnit.common.InstanceIdentifier;
import com.bbn.akbc.neolearnit.common.LearnItConfig;
import com.bbn.akbc.neolearnit.mappings.groups.Mappings;
import com.bbn.akbc.neolearnit.observations.label.LabelPattern;

import java.io.File;

public class EventMentionLabelItSelfLabeler implements MappingsLabeler {
    public static void main(String[] args) throws Exception{
        String paramPath = args[0];
        LearnItConfig.loadParams(new File(paramPath));
        String autogeneratedMappingsPath = args[1];
        String outputLabeledMappingsPath = args[2];
        EventMentionLabelItSelfLabeler eventMentionLabelItSelfLabeler = new EventMentionLabelItSelfLabeler();
        Mappings mappings = Mappings.deserialize(new File(autogeneratedMappingsPath), true);
        Mappings labeledMappings = eventMentionLabelItSelfLabeler.LabelMappings(mappings, new Annotation.InMemoryAnnotationStorage()).convertToMappings();
        labeledMappings.serialize(new File(outputLabeledMappingsPath), true);
    }

    @Override
    public Annotation.InMemoryAnnotationStorage LabelMappings(Mappings original, Annotation.InMemoryAnnotationStorage labeledMappings) throws Exception {
        for (InstanceIdentifier instanceIdentifier : original.getSeedInstances()) {
            if(instanceIdentifier.getSlot0SpanningType() == InstanceIdentifier.SpanningType.EventMention && instanceIdentifier.getSlot1SpanningType() == InstanceIdentifier.SpanningType.Empty){
                String eventType = instanceIdentifier.getSlotEntityType(0);
                if(eventType.contains("STEP3:")){
                    // TODO: Remove this.
                    eventType = eventType.replace("STEP3:","");
                    labeledMappings.addAnnotation(instanceIdentifier, new LabelPattern(eventType, Annotation.FrozenState.FROZEN_GOOD));
                }
            }
        }
        return labeledMappings;
    }
}
